events {
    worker_connections 1024;
}

stream {
    upstream backend {
        server api1:8080;
        server api2:8080;
    }
    server {
        listen 9999;
        proxy_pass backend;
        proxy_connect_timeout 1s;
    }
}
