events {
    worker_connections 128;
}

http {
    access_log off;
    error_log /dev/null crit;

    upstream api_backend {
        server api-1:8080;
        server api-2:8080;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 5s;
        }

        location /ready {
            proxy_pass http://api_backend/ready;
            proxy_http_version 1.1;
            proxy_read_timeout 5s;
        }
    }
}
